Repository AY1920S1-CS2113T-F09-1/main, pull requests merged in 2019-11, with the labels that each got.

#210 Fixes the Parser Bug where it will incorrectly read Commands that are…
  src/main/java/executor/command/Executor.java
  src/main/java/interpreter/Parser.java
Labels: bug, priority.High, severity.Medium

#216 Created new Logo for DUKE$$$ to solve issue #215
  src/main/java/ui/Ui.java
Labels: difficulty.Easy, enhancement, priority.High

#118 Added exceptions handling for weather feature to resolve issue #117, #206 , #161 , #169 , #160 , #148, #147 ,#136 ,#135
  savedTask.txt
  savedWallet.txt
  src/main/java/executor/command/CommandWeather.java
Labels: severity.High, type.enhancement

#230 Architecture update
  savedTask.txt
  src/main/java/executor/command/Command.java
  src/main/java/executor/command/CommandAdd.java
  src/main/java/executor/command/CommandAddIncomeReceipt.java
  src/main/java/executor/command/CommandAddReceipt.java
  src/main/java/executor/command/CommandAddSpendingReceipt.java
  src/main/java/executor/command/CommandBlank.java
  src/main/java/executor/command/CommandBye.java
  src/main/java/executor/command/CommandConvert.java
  src/main/java/executor/command/CommandDateList.java
  src/main/java/executor/command/CommandDelete.java
  src/main/java/executor/command/CommandDisplayBalance.java
  src/main/java/executor/command/CommandDisplayExpenditure.java
  src/main/java/executor/command/CommandDiv.java
  src/main/java/executor/command/CommandError.java
  src/main/java/executor/command/CommandFind.java
  src/main/java/executor/command/CommandGetSpendingByDay.java
  src/main/java/executor/command/CommandGetSpendingByMonth.java
  src/main/java/executor/command/CommandGetSpendingByYear.java
  src/main/java/executor/command/CommandHelp.java
  src/main/java/executor/command/CommandList.java
  src/main/java/executor/command/CommandMarkDone.java
  src/main/java/executor/command/CommandMul.java
  src/main/java/executor/command/CommandNewTask.java
  src/main/java/executor/command/CommandQueue.java
  src/main/java/executor/command/CommandReminder.java
  src/main/java/executor/command/CommandSchedule.java
  src/main/java/executor/command/CommandSub.java
  src/main/java/executor/command/CommandTagList.java
  src/main/java/executor/command/CommandType.java
  src/main/java/executor/command/CommandUpdateBalance.java
  src/main/java/executor/command/CommandWeather.java
  src/main/java/executor/command/Executor.java
  src/main/java/executor/task/Deadline.java
  src/main/java/executor/task/Task.java
  src/main/java/executor/task/TaskList.java
  src/main/java/executor/task/ToDo.java
  src/main/java/interpreter/Interpreter.java
  src/main/java/interpreter/Parser.java
  src/main/java/storage/StorageManager.java
  src/main/java/storage/StorageTask.java
  src/main/java/storage/StorageWallet.java
  src/main/java/ui/ReceiptTracker.java
  src/main/java/ui/Ui.java
  src/main/java/ui/UiCode.java
  src/main/java/ui/Wallet.java
  src/main/java/utils/InfoCapsule.java
  src/test/java/CommandAddReceiptTest.java
  src/test/java/CommandDisplayBalanceTest.java
  src/test/java/CommandDisplayExpenditureTest.java
  src/test/java/CommandMarkDoneTest.java
  src/test/java/CommandQueueTest.java
  src/test/java/StorageTaskTest.java
  src/test/java/StorageWalletTest.java
  src/test/java/ToDoTest.java
  src/test/java/ui/ReceiptTrackerTest.java
  testDataLoad.txt
  testDataSave.txt
Labels: priority.High, type.task

#233 added jUnit and resolved checkstyle issues to resolve issue #231
  src/test/java/ui/CommandReminderTest.java
Labels: difficulty.Average, type.Test

#239 Fixed bug where CommandConvert will exit the programme when incorrect…
  src/main/java/executor/command/CommandConvert.java
Labels: bug

#243 Fixed JUnit test for CommandDateListTest.
  src/main/java/executor/Executor.java
  src/main/java/executor/accessors/AccessDeny.java
  src/main/java/executor/accessors/AccessPieChartData.java
  src/main/java/executor/accessors/AccessTaskList.java
  src/main/java/executor/accessors/AccessWallet.java
  src/main/java/executor/accessors/AccessWalletBalance.java
  src/main/java/executor/accessors/AccessWalletExpenses.java
  src/main/java/executor/accessors/Accessor.java
  src/main/java/storage/StorageManager.java
  src/main/java/ui/gui/HomeWindow.java
  src/main/java/ui/gui/MainWindow.java
  src/main/java/utils/AccessType.java
  src/test/java/CommandDateListTest.java
  testWalletDataLoad.txt
  testWalletDataSave.txt
Labels: bug, priority.Low

#245 Enhanced Toast Pop-up so it gives more time for the user to read the …
  src/main/java/ui/gui/Toast.java
Labels: difficulty.Easy, type.enhancement

#251 Fixed Gui bug
  savedTask.txt
  savedWallet.txt
  src/main/java/ui/gui/HomeWindow.java
  src/main/java/ui/gui/MainWindow.java
Labels: bug

#273 Refactored export Command successfully to be able to export wallet data into a useful display in excel and resolves issue #271
  savedWallet.txt
  src/main/java/executor/command/CommandExport.java
Labels: difficulty.Hard, priority.High, severity.High

#269 New feature that shows major expenses in the wallet
  savedTask.txt
  savedWallet.txt
  src/main/java/executor/command/CommandMajorExpense.java
  src/main/java/executor/command/CommandType.java
  src/main/java/storage/StorageManager.java
  src/main/java/ui/ReceiptTracker.java
  src/test/java/CommandMajorExpenseTest.java
Labels: difficulty.Average, enhancement

#261 New CommandTrack feature allows User to track expenditure based on <tag>
  savedTask.txt
  savedWallet.txt
  src/main/java/executor/command/Command.java
  src/main/java/executor/command/CommandAddIncomeReceipt.java
  src/main/java/executor/command/CommandAddSpendingReceipt.java
  src/main/java/executor/command/CommandGetSpendingByDay.java
  src/main/java/executor/command/CommandGetSpendingByMonth.java
  src/main/java/executor/command/CommandGetSpendingByWeek.java
  src/main/java/executor/command/CommandGetSpendingByYear.java
  src/main/java/executor/command/CommandPercent.java
  src/main/java/executor/command/CommandTagList.java
  src/main/java/executor/command/CommandTrackTag.java
  src/main/java/executor/command/CommandType.java
  src/main/java/executor/command/CommandUntrackTag.java
  src/main/java/executor/command/CommandUpdateBalance.java
  src/main/java/interpreter/Parser.java
  src/main/java/storage/StorageManager.java
  src/main/java/storage/StorageWallet.java
  src/main/java/ui/ReceiptTracker.java
  src/main/java/ui/Wallet.java
  src/main/java/ui/gui/HomeWindow.java
  src/main/java/ui/gui/MainWindow.java
  src/main/resources/view/HomeWindow.fxml
  src/test/java/CommandAddReceiptTest.java
  src/test/java/CommandDateListTest.java
  src/test/java/CommandMajorExpenseTest.java
  src/test/java/CommandTagListTest.java
  src/test/java/StorageWalletTest.java
  src/test/java/ui/CommandTrackTagTest.java
  src/test/java/ui/CommandUntrackTagTest.java
  src/test/java/ui/ReceiptTrackerTest.java
  testWalletDataLoad.txt
  testWalletDataSave.txt
Labels: difficulty.Average, enhancement, priority.High, type.task

#280 Adds CommandClearCli which allows the User to clear the current CLI Display
  src/main/java/executor/command/CommandClearCli.java
  src/main/java/executor/command/CommandType.java
  src/main/java/ui/UiCode.java
  src/main/java/ui/gui/CommandLineDisplay.java
  src/main/java/ui/gui/MainWindow.java
  src/test/java/ui/CommandClearCliTest.java
Labels: difficulty.Easy, enhancement, priority.Low

#293 Fixes errors arising from the refactoring of Receipts to Income and E…
  src/main/java/executor/accessors/AccessPieChartData.java
  src/main/java/executor/command/CommandAddIncomeReceipt.java
  src/main/java/executor/command/CommandAddSpendingReceipt.java
  src/main/java/ui/Receipt.java
  src/main/java/ui/Wallet.java
  src/main/java/ui/gui/HomeWindow.java
  src/test/java/CommandAddReceiptTest.java
  src/test/java/CommandDateListTest.java
  src/test/java/CommandMajorExpenseTest.java
  src/test/java/CommandStatisticsTest.java
  src/test/java/CommandTagListTest.java
  src/test/java/ui/ReceiptTest.java
  src/test/java/ui/WalletTest.java
  testWalletDataSave.txt
Labels: bug, difficulty.Hard, priority.High, severity.High

#294 Bugfix balance refactor
  src/main/java/ui/ReceiptTracker.java
Labels: bug

#297 Managed to fix reminder and viewschedule related bugs
  savedTask.txt
  src/main/java/executor/command/CommandReminder.java
  src/main/java/executor/task/Deadline.java
  src/main/java/executor/task/Task.java
  src/main/java/executor/task/TaskList.java
  src/test/java/ui/CommandReminderTest.java
Labels: bug, difficulty.Hard, priority.High

#306 Tester aid
  src/main/java/executor/task/Deadline.java
  src/main/java/executor/task/Task.java
  src/main/java/executor/task/TaskList.java
  src/main/java/storage/StorageTask.java
  src/main/java/storage/StorageWallet.java
  src/main/java/ui/gui/HomeWindow.java
  src/main/java/ui/gui/MainWindow.java
Labels: bug, priority.High

#307 Fixed bug that did not allow Help command to properly show descriptio…
  src/main/java/executor/command/CommandHelp.java
  src/main/java/executor/command/CommandNewTask.java
Labels: bug

#277 New feature CommandEdit added with Junit testing
  data.csv
  savedWallet.txt
  src/main/java/executor/command/CommandEdit.java
  src/main/java/executor/command/CommandGetSpendingByDay.java
  src/main/java/executor/command/CommandGetSpendingByMonth.java
  src/main/java/executor/command/CommandGetSpendingByWeek.java
  src/main/java/executor/command/CommandGetSpendingByYear.java
  src/main/java/executor/command/CommandHelp.java
  src/main/java/executor/command/CommandType.java
  src/test/java/CommandEditTest.java
  src/test/java/CommandGetSpendingByDayTest.java
  src/test/java/CommandGetSpendingByMonthTest.java
  src/test/java/CommandGetSpendingByWeekTest.java
  src/test/java/CommandGetSpendingByYearTest.java
  testWalletDataSave.txt
Labels: difficulty.Average, priority.Medium, severity.Medium
